root = "."
tmp_dir = "tmp"
build_delay = 1000
log = "air.log"
clear_tmp = true

[build]
  bin = "app"
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = ["README.md"]
  include_ext = [".go", ".tpl", ".tmpl", ".html"]
  exclude_file = ["*.test.go"]
  exclude_dir = ["tmp/*"]
  exclude_file = ["tmp/*"]
  main = "main.go"

[tool]
  pid_file = "air.pid"
